[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "pandoc"]

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start" 